name: Build and test on Linux

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC",
            id: gcc, artifact: "Linux.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++",
            boost: "sudo apt-get update && sudo apt-get install libboost-all-dev -y"
          }
        # - {
        #     name: "macOS Latest Clang", artifact: "macOS.tar.xz",
        #     os: macos-latest,
        #     id: mac,
        #     build_type: "Release", cc: "clang", cxx: "clang++",
        #     boost: "brew update && brew install boost"
        #   }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.23.x'
      - name: Install Boost
        run: ${{ matrix.config.boost }}
      - name: CMake Configure 
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
      - name: CMake Build
        run: cmake --build build --config ${{ matrix.config.build_type }} --target test
      - name: Test
        run: |
          cd build
          ./pbn_test